In [40]:
import numpy as np 
x=int(input("num of student "))
y=int(input("num of subj "))
k=np.array([])
for i in range (x):
    temparray=np.array([])
    for j in range(y):
        temp=int(input("num of marks "))
        temparray = np.append(temparray,temp)
    print(temparray)
    k = np.concatenate((k,temparray))
k = k.reshape(x,y)
print(k)
o=np.sum(k,axis=1)
print(o)
if j >=90:
    print("A+")
elif j >=80:
    print("A")
elif j >=70:
    print("B+")
elif j >= 60:
    print("B")
elif j>= 50:
    print("c")
else:
    print("fail")


num of student 2
num of subj 3
num of marks 15
num of marks 50
num of marks 80
[15. 50. 80.]
num of marks 91
num of marks 70
num of marks 80
[91. 70. 80.]
[[15. 50. 80.]
 [91. 70. 80.]]
[145. 241.]
fail
